# THIS FILE IS AUTOGENERATED! DO NOT EDIT!

FROM ubuntu:18.04

RUN \
	useradd \
		--comment 'User' \
		--home-dir '/home/user' \
		--expiredate '' \
		--inactive '-1' \
		--create-home \
		--password 'password' \
		--shell '/bin/bash' \
		--user-group \
		'user'; \
	mkdir -p '/user'
USER user
WORKDIR '/home/user'

ENTRYPOINT [ "bash" ]
