ARG ARG_DISTRO_VARIANT
FROM ubuntu:${ARG_DISTRO_VARIANT}

RUN : \
	&& DEBIAN_FRONTEND='noninteractive' apt-get update -y \
	&& DEBIAN_FRONTEND='noninteractive' apt-get install -y --no-install-recommends 'apt-utils' 'apt-transport-https' \
	&& DEBIAN_FRONTEND='noninteractive' apt-get upgrade -y

RUN useradd \
	--comment 'Fox' \
	--home-dir '/home/fox' \
	--expiredate '' \
	--inactive '-1' \
	--create-home \
	--password 'password' \
	--shell '/bin/bash' \
	--user-group \
	'fox' \
	&& mkdir -p '/fox' \
	&& printf '%s\n' "$ARG_GIT_COMMIT" > '/fox/git-commit'

WORKDIR '/home/fox'
USER fox
